### ISSUE TITLE
Why elem[0].value?

### ISSUE THREAD

**Issue by lsiden** [Finance-e/angular-price-format#1]
Just curious.  In angular-price-format.js, the format and parser callback functions each take a single argument, 'a' and 'viewValue', respectively.  Why are these not used instead of elem[0].value and ctrl.$modelValue?

If I set a breakpoint in the the $parsers() callback, I can verify that these return the same value.

On the other hand, if I set a breakpoint in the $formatters() callback, I can verify that a === "0" while ctrl.$modelValue === 0.  I would have thought that these should be the same.  I guess that's really an Angular question.

**Comment by thomfilg** [comment]
Hello Isiden,
Sorry for being slow to respond, the github doesn't sent me an email notification...

About your doubt: there's no rational cause! I dont have good skills in angularjs. So, i did the code, and it worked! Probably use the variable that you suggested, it will works too!

:smile:
