### ISSUE TITLE
Update angular dependency

### ISSUE THREAD

**Issue by miclill** [Finance-e/angular-price-format#6]
Unable to find a suitable version for angular, please choose one:
    1) angular#~1.3.1 which resolved to 1.3.20 and is required by angular-price-format#0.1.0
    2) angular#1.4.8 which resolved to 1.4.8 and is required by angular-animate#1.4.8, angular-cookies#1.4.8, angular-mocks#1.4.8, angular-resource#1.4.8, angular-route#1.4.8, angular-sanitize#1.4.8

Thanks for the directive! :+1:

**Comment by thomfilg** [comment]
Hello miclill, i always use the latest angular version. But the tested angular version is ~1.3.1.

See in bower file: https://github.com/Finance-e/angular-price-format/blob/master/bower.json
