### ISSUE TITLE
Dynamic thousand and currency separators

### ISSUE THREAD

**Issue by dhaval85** [Finance-e/angular-price-format#7]
Hello,

I'm dynamically changing the thousand separator and cent separator based on a currency selection by user on the fly. However the change is not being reflected until I change the amount in text box. 

Regards, 
Dhaval

**Comment by thomfilg** [comment]
Hello dhaval85,

i think this problem occurs because angular's directive binds only the variable value. You can solve this issue creating in your controller some watchers who updates the value variable.

See https://docs.angularjs.org/api/ng/type/$rootScope.Scope for more watchers details

**Comment by dhaval85** [comment]
Hello @tigredonorte ,

It's just a workaround what you've suggested. I was looking for a proper solution. 

Thanks, 
Dhaval
